
name: Test Samsung X110 Build

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  test:
    name: Test Workflow
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test GitHub Actions
        run: |
          echo "YAML berhasil dibaca"
          echo "GitHub Actions berjalan"
